### ISSUE TITLE
[5] Add support for storage pressure

### ISSUE THREAD

**Issue by legraphista** [findie/expire-fs#2]
### Options
- [x] possibility to define total maximum usage of disk in percentage 
-  [x] possibility to define the minimum lifetime of the file so that is ignored if its too young

### Todo
- [x] if the percentage is met or exceeded, clean files from oldest to newest until the percentage drops below threshold
